from pathlib import Path
p = Path('/home/ubuntu/aios-overview/PREHLAD-AIOS-SYSTEMS.md')
s = p.read_text()
s = s.replace('# Prehľad workspace AiOS-SYSTEMS', '# AiOS-SYSTEMS: celkový prehľad a štruktúra projektov')
s = s.replace('_Read-only orientačný prehľad lokálneho workspace k 24. septembru 2026. Vypracoval Manus AI výlučne z dodaného inventára a zozbieraných výsledkov; nejde o test, bezpečnostný audit ani súpis citlivého obsahu._', '_Prehľad pracovného priečinka k 24. septembru 2026. Vypracoval Manus AI na základe adresárovej štruktúry, dokumentácie a vybraných zdrojových súborov. Kontrola prebehla bez zmien v existujúcich súboroch._')
s = s.replace('**pracovný workspace s viacerými nezávislými materiálmi**, nie potvrdený monorepozitár ani jedna spustiteľná aplikácia', '**zbierka samostatných projektov a podkladov**, nie jedna aplikácia ani jeden spoločný repozitár')
s = s.replace('**21 koreňových priečinkov** a dva koreňové súbory', '**21 koreňových priečinkov vrátane skrytého `.claude`** a dva koreňové súbory')
s = s.replace(' [17]', '')
s = s.replace(' Súbor `project-findings.json` vedľa tejto správy uchováva dodaný inventár, všetkých 15 zozbieraných výsledkov a prázdny zoznam zlyhaní ako internú validačnú stopu.', '')
s = s.replace('passive[Pasívne priečinky]', 'passive[Ostatné priečinky bez obsahovej kontroly]')
s = s.replace('Pasívny priečinok; obsah nebol prehliadaný.', 'Zaznamenaný názov; obsah neprehliadaný.')
s = s.replace('Pasívny priečinok; obsah neotvorený.', 'Zaznamenaný názov; obsah neotvorený.')
s = s.replace('Pasívny priečinok; názov', 'Obsah neprehliadaný; názov')
s = s.replace('Pasívny priečinok; obsah neprehliadaný.', 'Zaznamenaný názov; obsah neprehliadaný.')
s = s.replace('Pasívny priečinok; pozorované iba kategórie', 'Pozorované iba kategórie')
s = s.replace('Rovnako pasívne priečinky nemajú v tejto správe žiadne obsahové tvrdenia.', 'Pri priečinkoch bez obsahovej kontroly prehľad nevyvodzuje závery o ich obsahu ani aktívnom používaní.')
s = s.replace('Takéto závery by vyžadovali samostatný, výslovne povolený audit s kontrolou konkrétnej vetvy, jej histórie, závislostí a runtime overením.', 'Na určenie aktuálnej pracovnej kópie by bolo potrebné porovnať konkrétne vetvy a ich históriu; funkčnosť by bolo potrebné overiť samostatnými testami.')
s = s.replace('file:///mnt/', '/mnt/')
s = '\n'.join(line for line in s.splitlines() if not line.startswith('[17]:')) + '\n'
p.write_text(s)
print(f'Refined: {p}')
